# Write it!

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'yarn_cache/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RescueModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%W': '()'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/NestedTernaryOperator:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false
