# Write it!

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'yarn_cache/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
